version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - app-network

  resource-service:
    build:
      context: ./resourse-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - resource-app.env
    networks:
      - app-network

  song-service:
    build:
      context: ./song-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    env_file:
      - song-app.env
    networks:
      - app-network

  song-service-2:
    build:
      context: ./song-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
    env_file:
      - song-app.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge