FROM openjdk:17.0.1-jdk-slim

WORKDIR /app

COPY target/resourse-service-0.0.1-SNAPSHOT.jar /app/resourse-service-0.0.1-SNAPSHOT.jar

EXPOSE 8080

CMD ["java", "-jar", "resourse-service-0.0.1-SNAPSHOT.jar"]